***

## pandas综合练习

####  实训提交说明：
- 位置：实训文件统一放置于/0.Teacher/Exercise/第一阶段-python数据分析/02下
- 文件名：请先复制该notebook文件，并重新命名为(课程名)+(您姓名的全拼)，并按要求完成后保存
- 时间：课程结束后的第二天前提交。
- 注意：请勿抄袭，移动，修改，删除其他同学和原始空白的练习文件。
***

##### 说明：我们下面做的这一系列操作都属于数据预处理的范畴。在做实际machine learning问题的时候，很多时候我们都需要对数据进行预处理操作，方便后续的建模。

### 1.创建一个边界值为1而内部都是0的数组，图例如下：

    [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
    [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
    [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
    [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
    [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
    [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
    [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
    [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
    [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
    [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


[提示：]解此题可以先把所有值都设置为1，这是大正方形；其次，把边界除外小正方形全部设置为0。
本题用到numpy的切片原理。多维数组同样遵循x[start:stop:step]的原理。

In [1]:
%config ZMQInteractiveShell.ast_node_interactivity='all'

In [17]:
import numpy as np
td = np.ones(shape=[10, 10])
for i in range(1, 9):
    td[i][1:9] = np.zeros(shape=[1, 8])
td

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [51]:
import numpy as np
a = np.ones((10, 10))
a[1:9, 1:9] = 0
a

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

### 2.生成一个随机的5*5矩阵，找出最大值和最小值，然后把最大值和最小值分别用1和0表示，其他值则介于在0和1中间

In [22]:
a = np.random.rand(5,5)
min = np.amin(a)
max = np.amax(a)
a[a == min] = 0
a[a == max] = 1
a
min, max

array([[0.24190675, 0.86547417, 0.16769585, 0.79248001, 0.13007535],
       [0.941667  , 1.        , 0.05737052, 0.78743868, 0.64077441],
       [0.10312102, 0.30746814, 0.6531543 , 0.22084433, 0.13572411],
       [0.47234085, 0.71400628, 0.        , 0.17227781, 0.90096432],
       [0.29062356, 0.36786516, 0.94202949, 0.33223932, 0.57941327]])

(0.024303448269316963, 0.9545928902578165)

In [52]:
a = np.random.rand(5,5)
a
a[a == a.min()] = 0
a[a == a.max()] = 1
a

array([[0.98709187, 0.09546853, 0.53959086, 0.05753427, 0.87788638],
       [0.44296069, 0.14283588, 0.80518148, 0.83203972, 0.31275981],
       [0.12564585, 0.15843722, 0.51789562, 0.33764637, 0.94876179],
       [0.17503913, 0.18188885, 0.22592425, 0.37412205, 0.70888813],
       [0.00610486, 0.78884012, 0.57322323, 0.27396654, 0.79480391]])

array([[1.        , 0.09546853, 0.53959086, 0.05753427, 0.87788638],
       [0.44296069, 0.14283588, 0.80518148, 0.83203972, 0.31275981],
       [0.12564585, 0.15843722, 0.51789562, 0.33764637, 0.94876179],
       [0.17503913, 0.18188885, 0.22592425, 0.37412205, 0.70888813],
       [0.        , 0.78884012, 0.57322323, 0.27396654, 0.79480391]])

### 3.pandas操作1


#### 3.1 构建三个Series，分别是一系列商品的单价，计量单位，和数量。至于是什么商品什么计量单位由大家自己决定。


In [3]:
import pandas as pd
price = pd.Series([2, 30, 10], name='Price')
unit = pd.Series(['瓶', '盒', '斤'], name='Unit')
num = pd.Series([2, 5, 9], name='Number')


#### 3.2 然后把这三个Series合并成一个DataFrame

In [ ]:
df = pd.concat([price, unit, num], axis=1)
df = pd.DataFrame(df, index=['水', '巧克力', '米'])
df

### 4.pandas操作2

#### 4.1  0.Teacher/data/文件夹下有个文件叫做titanic.csv ，这个文件包含了在titanic事件中乘客的存活情况。请把这个文件读入成一个pandas dataframe

In [40]:
path = '../../../data/titanic.csv'
df = pd.read_csv(path)
df.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

#### 4.2 把每一列中的sex，sex为male的都改成1，sex为female的改成0,

In [41]:
df.loc[:,'Sex'] = df['Sex'].str.replace('female', '0')
df.loc[:,'Sex'] = df['Sex'].str.replace('male', '1')
df.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name Sex   Age  SibSp  Parch  \
0                            Braund, Mr. Owen Harris   1  22.0      1      0   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...   0  38.0      1      0   
2                             Heikkinen, Miss. Laina   0  26.0      0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)   0  35.0      1      0   
4                           Allen, Mr. William Henry   1  35.0      0      0   

             Ticket     Fare Cabin Embarked  
0         A/5 21171   7.2500   NaN        S  
1          PC 17599  71.2833   C85        C  
2  STON/O2. 3101282   7.9250   NaN        S  
3            113803  53.1000  C123        S  
4            373450   8.0500   NaN        S

In [53]:
!pwd

/home/jxy11/run/0.Teacher/Exercise/第一阶段-python数据分析/02


In [56]:
path = '/home/jxy11/run/0.Teacher/data/titanic.csv'
pe = pd.read_csv(path)
# 方法一
pe.Sex = pe.Sex.apply(lambda x:1 if x == 'male' else 0)
# 方法二
# pe.loc[pe["Sex"]=="male",["Sex"]] = 1
# pe.loc[pe["Sex"] == "female" ,["Sex"]] = 0
pe.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name Sex   Age  SibSp  Parch  \
0                            Braund, Mr. Owen Harris   1  22.0      1      0   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...   0  38.0      1      0   
2                             Heikkinen, Miss. Laina   0  26.0      0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)   0  35.0      1      0   
4                           Allen, Mr. William Henry   1  35.0      0      0   

             Ticket     Fare Cabin Embarked  
0         A/5 21171   7.2500   NaN        S  
1          PC 17599  71.2833   C85        C  
2  STON/O2. 3101282   7.9250   NaN        S  
3            113803  53.1000  C123        S  
4            373450   8.0500   NaN        S

#### 4.3 把Cabin中的NaN都填充成0 (使用fillna方法)

In [57]:
pe.Cabin.fillna(0, inplace=True)
pe.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name Sex   Age  SibSp  Parch  \
0                            Braund, Mr. Owen Harris   1  22.0      1      0   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...   0  38.0      1      0   
2                             Heikkinen, Miss. Laina   0  26.0      0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)   0  35.0      1      0   
4                           Allen, Mr. William Henry   1  35.0      0      0   

             Ticket     Fare Cabin Embarked  
0         A/5 21171   7.2500     0        S  
1          PC 17599  71.2833   C85        C  
2  STON/O2. 3101282   7.9250     0        S  
3            113803  53.1000  C123        S  
4            373450   8.0500     0        S

In [42]:
df.loc[:, 'Cabin'] = df['Cabin'].fillna(0)
df.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name Sex   Age  SibSp  Parch  \
0                            Braund, Mr. Owen Harris   1  22.0      1      0   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...   0  38.0      1      0   
2                             Heikkinen, Miss. Laina   0  26.0      0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)   0  35.0      1      0   
4                           Allen, Mr. William Henry   1  35.0      0      0   

             Ticket     Fare Cabin Embarked  
0         A/5 21171   7.2500     0        S  
1          PC 17599  71.2833   C85        C  
2  STON/O2. 3101282   7.9250     0        S  
3            113803  53.1000  C123        S  
4            373450   8.0500     0        S

#### 4.4 现在我们想把乘客按照年龄做一个分类
- 年龄在0-11岁的为0类,12-22为1类，23-33为2类，34-44为3类，45-55为4类，56-66为5类，其余为6类
- 请做把Age改成乘客的年龄类别，如果年龄有缺失，就放入乘客的平均年龄


In [59]:
pe.Age.fillna(pe.Age.mean().round(), inplace=True)
def classfy(age):
    if age > 0 and age <= 11:
        return '0类'
    elif age > 11 and age <= 22:
        return '1类'
    elif age > 22 and age <= 33:
        return '2类'
    elif age>=34 and age<=44:
        return "3类"
    elif age>=45 and age<=55:
        return "4类"
    elif age>=56 and age<=66:
        return "5类"
    else:
        return "6类"
    
pe.Age = pe.Age.apply(classfy)
pe.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name Sex Age  SibSp  Parch  \
0                            Braund, Mr. Owen Harris   1  1类      1      0   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...   0  3类      1      0   
2                             Heikkinen, Miss. Laina   0  2类      0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)   0  3类      1      0   
4                           Allen, Mr. William Henry   1  3类      0      0   

             Ticket     Fare Cabin Embarked  
0         A/5 21171   7.2500     0        S  
1          PC 17599  71.2833   C85        C  
2  STON/O2. 3101282   7.9250     0        S  
3            113803  53.1000  C123        S  
4            373450   8.0500     0        S

In [48]:
bins = [0, 12, 23, 34, 45, 56, 67]
df.loc[:, 'Age'] = df['Age'].fillna(df.mean()['Age'])
df.loc[:, 'Age'] = pd.cut(df['Age'], bins, labels=['1类', '2类', '3类', '4类', '5类', '6类'])
df

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name Sex Age  SibSp  Parch  \
0                              Braund, Mr. Owen Harris   1  2类      1      0   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...   0  4类      1      0   
2                               Heikkinen, Miss. Laina   0  3类      0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)   0  4类      1      0   
4                             Allen, Mr. William Henry   1  4类      0      0   
..                                                 ...  ..  ..    ...    ...   
886                              Montvila, Rev. Juozas   1  3类      0      0   
887                       Graham, Miss. Margaret Edith   0  2类      0      0   
888           Johnston, Miss. Catherine Helen "Carrie"   0  3类      1      2   
889                              Behr, Mr. Karl Howell   1  3类      0      0   
890                                Dooley, Mr. Patrick   1  3类      0      0   

               Ticket     Fare Cabin Embarked  
0           A/5 21171   7.2500     0        S  
1            PC 17599  71.2833   C85        C  
2    STON/O2. 3101282   7.9250     0        S  
3              113803  53.1000  C123        S  
4              373450   8.0500     0        S  
..                ...      ...   ...      ...  
886            211536  13.0000     0        S  
887            112053  30.0000   B42        S  
888        W./C. 6607  23.4500     0        S  
889            111369  30.0000  C148        C  
890            370376   7.7500     0        Q  

[891 rows x 12 columns]

### 5.pandas操作3


#### 5.1 读入0.Teacher/data/下NVDA.csv中的数据


In [50]:
path = '../../../data/NVDA.csv'
df = pd.read_csv(path)
df.head()

Date      Open      High       Low     Close  Adj Close    Volume
0  1999-01-22  1.750000  1.953125  1.552083  1.640625   1.523430  67867200
1  1999-01-25  1.770833  1.833333  1.640625  1.812500   1.683028  12762000
2  1999-01-26  1.833333  1.869792  1.645833  1.671875   1.552448   8580000
3  1999-01-27  1.677083  1.718750  1.583333  1.666667   1.547611   6109200
4  1999-01-28  1.666667  1.677083  1.651042  1.661458   1.542776   5688000

In [61]:
path = '../../../data/NVDA.csv'
df = pd.read_csv(path, index_col='Date', parse_dates=['Date'])
df.head()

Open      High       Low     Close  Adj Close    Volume
Date                                                                   
1999-01-22  1.750000  1.953125  1.552083  1.640625   1.523430  67867200
1999-01-25  1.770833  1.833333  1.640625  1.812500   1.683028  12762000
1999-01-26  1.833333  1.869792  1.645833  1.671875   1.552448   8580000
1999-01-27  1.677083  1.718750  1.583333  1.666667   1.547611   6109200
1999-01-28  1.666667  1.677083  1.651042  1.661458   1.542776   5688000

In [64]:
df.describe()

Open         High          Low        Close    Adj Close  \
count  4654.000000  4654.000000  4654.000000  4654.000000  4654.000000   
mean     18.872888    19.222090    18.513574    18.879564    18.091126   
std      22.025278    22.346668    21.662627    22.048935    22.093697   
min       1.395833     1.421875     1.333333     1.364583     1.267107   
25%       8.510000     8.755000     8.245261     8.505000     7.897462   
50%      13.810000    14.090000    13.500000    13.814167    12.832797   
75%      19.770000    20.129999    19.505000    19.789167    18.774976   
max     166.330002   168.500000   164.610001   167.500000   167.500000   

             Volume  
count  4.654000e+03  
mean   1.632563e+07  
std    1.204002e+07  
min    4.920000e+05  
25%    8.721475e+06  
50%    1.373830e+07  
75%    2.041408e+07  
max    2.307714e+08

#### 5.2 请计算nvda股票Adj Close每天的log return

In [66]:
type(df['Adj Close'])
df['log return'] = np.log(df['Adj Close'] / df['Adj Close'].shift(1))
df.head()

pandas.core.series.Series

Open      High       Low     Close  Adj Close    Volume  \
Date                                                                      
1999-01-22  1.750000  1.953125  1.552083  1.640625   1.523430  67867200   
1999-01-25  1.770833  1.833333  1.640625  1.812500   1.683028  12762000   
1999-01-26  1.833333  1.869792  1.645833  1.671875   1.552448   8580000   
1999-01-27  1.677083  1.718750  1.583333  1.666667   1.547611   6109200   
1999-01-28  1.666667  1.677083  1.651042  1.661458   1.542776   5688000   

            log return  
Date                    
1999-01-22         NaN  
1999-01-25    0.099630  
1999-01-26   -0.080762  
1999-01-27   -0.003121  
1999-01-28   -0.003129

#### 5.3 请找出nvda股票涨幅最大的10天

In [67]:
df['increase'] = (df['Adj Close'] - df['Adj Close'].shift(1)) / df['Adj Close']
in_top = df['increase'].sort_values(ascending = False).iloc[:10]
in_top

Date
2000-03-07    0.297824
2003-05-09    0.248479
2001-01-03    0.234824
2016-11-11    0.229624
2000-03-13    0.209380
2000-12-22    0.204991
2000-12-08    0.185930
2000-04-05    0.182004
2003-02-14    0.180233
1999-08-19    0.175115
Name: increase, dtype: float64

#### 5.4 将这十天的股票信息都输出来

In [70]:
df.sort_values(by = 'increase', ascending=False).iloc[:10]

Open       High        Low      Close  Adj Close     Volume  \
Date                                                                           
2000-03-07   6.250000   7.270833   5.979167   6.942708   6.446771   48805200   
2003-05-09   6.276667   7.176667   6.100000   7.123333   6.614493  230771400   
2001-01-03   4.833333   6.572917   4.708333   6.520833   6.055031   22759200   
2016-11-11  79.510002  88.769997  78.500000  87.970001  87.635475   54335100   
2000-03-13   8.916667  12.500000   8.833333  12.437500  11.549053   60379200   
2000-12-22   5.020833   6.375000   5.020833   5.843750   5.426314   23727000   
2000-12-08   7.447917   8.333333   6.752600   8.291667   7.699371   21334800   
2000-04-05   6.312500   8.125000   5.989583   7.640625   7.094833   15990000   
2003-02-14   3.740000   4.016667   3.650000   4.013333   3.726649   88721100   
1999-08-19   1.994792   2.364583   1.927083   2.260417   2.098948   49174800   

            log return  increase  
Date                              
2000-03-07    0.353572  0.297824  
2003-05-09    0.285656  0.248479  
2001-01-03    0.267650  0.234824  
2016-11-11    0.260876  0.229624  
2000-03-13    0.234938  0.209380  
2000-12-22    0.229402  0.204991  
2000-12-08    0.205709  0.185930  
2000-04-05    0.200898  0.182004  
2003-02-14    0.198735  0.180233  
1999-08-19    0.192511  0.175115